import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import {
  assertGeneratedContent,
  desktopContractPaths,
  renderDesktopBindings,
} from '../scripts/generate-desktop-bindings.mjs';
import { validateMethodPolicy } from '../src/runtime-method-policy-validator.mjs';

const contractsRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

async function canonicalSources() {
  return Promise.all([
    readFile(desktopContractPaths.manifest),
    readFile(desktopContractPaths.fixtures),
    readFile(desktopContractPaths.policy),
  ]);
}

test('Rust handler/constants and TypeScript literals are derived byte-for-byte from one manifest', async () => {
  const sources = await canonicalSources();
  const rendered = renderDesktopBindings(...sources);
  const manifest = JSON.parse(sources[0].toString('utf8'));
  const [rustContract, rustHandler, typescript] = await Promise.all([
    readFile(desktopContractPaths.rustContract, 'utf8'),
    readFile(desktopContractPaths.rustHandler, 'utf8'),
    readFile(desktopContractPaths.typescript, 'utf8'),
  ]);
  assert.equal(rustContract, rendered.rustContract);
  assert.equal(rustHandler, rendered.rustHandler);
  assert.equal(typescript, rendered.typescript);
  assert.match(rustContract, /\("interruptTurn", "runtime_turn_interrupt"\)/u);
  assert.match(rustContract, /\("steerTurn", "runtime_turn_steer"\)/u);
  assert.match(rustContract, /\("stageAttachmentBytes", "raw_octet_stream", "json_envelope"\)/u);
  assert.match(rustContract, /\("readAttachmentPreview", "json_envelope", "raw_octet_stream"\)/u);
  assert.match(rustContract, /GENERATED_VOICE_TRANSCRIPT_MAX_UTF8_BYTES: usize = 65536/u);
  assert.match(rustContract, /GENERATED_ATTACHMENT_MAX_PER_DISPATCH: usize = 4/u);
  assert.match(rustContract, /\("\.tsx", "text", "text\/typescript"\)/u);
  assert.match(rustHandler, /commands::runtime_turn_interrupt/u);
  assert.match(rustHandler, /commands::runtime_turn_steer/u);
  assert.equal(
    [...rustHandler.matchAll(/commands::[a-z][a-z0-9_]*/gu)].length,
    Object.keys(manifest.commands).length,
  );
  assert.match(typescript, /export type NativeCommandName = keyof typeof NATIVE_COMMANDS/u);
  assert.match(typescript, /export const NATIVE_BINARY_TRANSPORTS/u);
  assert.match(typescript, /export const NATIVE_CONTENT_POLICY/u);
  assert.match(typescript, /export const NATIVE_ATTACHMENT_PICKER_ACCEPT/u);
  assert.match(typescript, /export type NativeEventName = keyof typeof NATIVE_EVENTS/u);
});

test('content policy rejects ambiguous formats and limits that could create unsendable drafts', async () => {
  const [manifestBytes, fixtureBytes, policyBytes] = await canonicalSources();
  const canonical = JSON.parse(manifestBytes.toString('utf8'));
  const render = (operation, expected) => {
    const manifest = structuredClone(canonical);
    operation(manifest.contentPolicy);
    assert.throws(
      () => renderDesktopBindings(Buffer.from(JSON.stringify(manifest)), fixtureBytes, policyBytes),
      expected,
    );
  };
  render((contentPolicy) => {
    contentPolicy.voice.transcriptMaxUtf8Bytes = contentPolicy.message.maxUtf8Bytes + 1;
  }, /desktop_content_policy_text_invalid/u);
  render((contentPolicy) => {
    contentPolicy.attachments.formats.push(structuredClone(contentPolicy.attachments.formats[0]));
  }, /desktop_content_policy_attachment_format_invalid/u);
  render((contentPolicy) => {
    contentPolicy.attachments.formats[0].kind = 'text';
  }, /desktop_content_policy_attachment_format_invalid/u);
  render((contentPolicy) => {
    contentPolicy.attachments.maxTextBytesPerDispatch = contentPolicy.attachments.maxTextBytes - 1;
  }, /desktop_content_policy_attachment_limits_invalid/u);
});

test('stale generated bytes fail closed', () => {
  assert.throws(
    () => assertGeneratedContent('// comment-only impostor\n', '// expected\n', 'native_bridge_handler.rs'),
    /desktop_bridge_bindings_stale:native_bridge_handler\.rs/u,
  );
});

test('manifest cannot smuggle a rogue Rust namespace into the generated handler', async () => {
  const [manifestBytes, fixtureBytes, policyBytes] = await canonicalSources();
  const manifest = JSON.parse(manifestBytes.toString('utf8'));
  manifest.commands.rogue = 'rogue::hidden';
  const fixtures = JSON.parse(fixtureBytes.toString('utf8'));
  fixtures.commands.rogue = {};
  assert.throws(
    () => renderDesktopBindings(Buffer.from(JSON.stringify(manifest)), Buffer.from(JSON.stringify(fixtures)), policyBytes),
    /desktop_bridge_commands_name_invalid/u,
  );
});

test('desktop bridge binding generation rejects duplicate wire commands', async () => {
  const [manifestBytes, fixtureBytes, policyBytes] = await canonicalSources();
  const manifest = JSON.parse(manifestBytes.toString('utf8'));
  manifest.commands.interruptTurn = manifest.commands.runtimeSend;
  assert.throws(
    () => renderDesktopBindings(Buffer.from(JSON.stringify(manifest)), fixtureBytes, policyBytes),
    /desktop_bridge_commands_duplicate_value/u,
  );
});

test('binary transport exceptions and every command fixture fail closed on shape or body-mode drift', async () => {
  const [manifestBytes, fixtureBytes, policyBytes] = await canonicalSources();
  const canonicalManifest = JSON.parse(manifestBytes.toString('utf8'));
  const canonicalFixtures = JSON.parse(fixtureBytes.toString('utf8'));
  const render = (mutateManifest, mutateFixtures, expected) => {
    const manifest = structuredClone(canonicalManifest);
    const fixtures = structuredClone(canonicalFixtures);
    mutateManifest?.(manifest);
    mutateFixtures?.(fixtures);
    assert.throws(
      () => renderDesktopBindings(
        Buffer.from(JSON.stringify(manifest)),
        Buffer.from(JSON.stringify(fixtures)),
        policyBytes,
      ),
      expected,
    );
  };

  render((manifest) => {
    manifest.binaryTransports.unknown = { request: 'raw_octet_stream', response: 'json_envelope' };
  }, null, /desktop_bridge_binary_transport_command_unknown/u);
  render((manifest) => {
    manifest.binaryTransports.stageAttachmentBytes.extra = true;
  }, null, /desktop_bridge_binary_transport_invalid/u);
  render((manifest) => {
    delete manifest.binaryTransports.stageAttachmentBytes.response;
  }, null, /desktop_bridge_binary_transport_invalid/u);
  render((manifest) => {
    manifest.binaryTransports.stageAttachmentBytes.request = 'bytes_maybe';
  }, null, /desktop_bridge_binary_transport_mode_invalid/u);
  render((manifest) => {
    manifest.binaryTransports.stageAttachmentBytes = { request: 'json_envelope', response: 'json_envelope' };
  }, null, /desktop_bridge_binary_transport_redundant/u);
  render(null, (fixtures) => {
    fixtures.commands.runtimeCall.args = {
      rawHeaders: {}, rawBodyBase64: '',
    };
  }, /desktop_bridge_json_fixture_request_invalid/u);
  render(null, (fixtures) => {
    fixtures.commands.runtimeCall.args.extra = true;
  }, /desktop_bridge_json_fixture_request_invalid/u);
  render(null, (fixtures) => {
    fixtures.commands.runtimeCall.response.extra = true;
  }, /desktop_bridge_json_fixture_response_invalid/u);
  render(null, (fixtures) => {
    fixtures.commands.stageAttachmentBytes.args = {
      input: { schemaVersion: 1 },
    };
  }, /desktop_bridge_binary_fixture_request_invalid/u);
  render(null, (fixtures) => {
    fixtures.commands.readAttachmentPreview.response = {
      schemaVersion: 1, result: null,
    };
  }, /desktop_bridge_binary_fixture_response_invalid/u);
});

test('fixture key drift and exact-turn mutation chain drift fail closed', async () => {
  const [manifestBytes, fixtureBytes, policyBytes] = await canonicalSources();
  const missingFixture = JSON.parse(fixtureBytes.toString('utf8'));
  delete missingFixture.commands.interruptTurn;
  assert.throws(
    () => renderDesktopBindings(manifestBytes, Buffer.from(JSON.stringify(missingFixture)), policyBytes),
    /desktop_bridge_fixtures_mismatch/u,
  );

  const wrongInterrupt = JSON.parse(fixtureBytes.toString('utf8'));
  wrongInterrupt.scenarios.interruptAccepted.runtimeMethod = 'runtime.send';
  assert.throws(
    () => renderDesktopBindings(manifestBytes, Buffer.from(JSON.stringify(wrongInterrupt)), policyBytes),
    /desktop_bridge_interrupt_chain_mismatch/u,
  );

  const wrongSteer = JSON.parse(fixtureBytes.toString('utf8'));
  wrongSteer.scenarios.steerAccepted.runtimeMethod = 'runtime.send';
  assert.throws(
    () => renderDesktopBindings(manifestBytes, Buffer.from(JSON.stringify(wrongSteer)), policyBytes),
    /desktop_bridge_steer_chain_mismatch/u,
  );
});

test('generator and runtime share an exact fail-closed method-policy validator', async () => {
  const [manifestBytes, fixtureBytes, policyBytes] = await canonicalSources();
  const canonical = JSON.parse(policyBytes.toString('utf8'));
  const mutate = (operation) => {
    const policy = structuredClone(canonical);
    operation(policy);
    return policy;
  };
  const cases = [
    ['root shape', mutate((policy) => { policy.rogue = true; }), /runtime_method_policy_shape_invalid/u],
    ['entry shape', mutate((policy) => { policy.methods['runtime.info'].rogue = true; }), /entry_shape_invalid/u],
    ['method name', mutate((policy) => {
      policy.methods['Runtime.info'] = policy.methods['runtime.info'];
      delete policy.methods['runtime.info'];
    }), /name_invalid/u],
    ['response', mutate((policy) => { policy.methods['runtime.info'].responseType = '   '; }), /response_invalid/u],
    ['boolean', mutate((policy) => { policy.methods['runtime.info'].rendererExposed = 'yes'; }), /boolean_invalid/u],
    ['mutation enum', mutate((policy) => { policy.methods['runtime.info'].mutationKind = 'other'; }), /enum_invalid/u],
    ['project enum', mutate((policy) => { policy.methods['runtime.info'].projectRequirement = 'other'; }), /enum_invalid/u],
    ['recovery enum', mutate((policy) => { policy.methods['runtime.info'].recoveryStrategy = 'other'; }), /enum_invalid/u],
    ['timeout', mutate((policy) => { policy.methods['runtime.info'].defaultTimeoutMs = 999; }), /timeout_invalid/u],
    ['recovery parity', mutate((policy) => { policy.methods['runtime.info'].recoveryStrategy = 'native_lifecycle'; }), /recovery_mismatch/u],
    ['attachments', mutate((policy) => { policy.methods['runtime.info'].attachmentsAllowed = true; }), /attachment_mismatch/u],
    ['renderer unavailable', mutate((policy) => { policy.methods['repository.get-snapshot'].recoveryStrategy = 'internal_unavailable'; }), /unavailable_exposed/u],
    ['runtime.send', mutate((policy) => { policy.methods['runtime.send'].responseType = 'other'; }), /runtime_send_must_be_typed_native_dispatch/u],
  ];
  for (const [label, policy, expected] of cases) {
    assert.throws(() => validateMethodPolicy(policy), expected, label);
    assert.throws(
      () => renderDesktopBindings(manifestBytes, fixtureBytes, Buffer.from(JSON.stringify(policy))),
      expected,
      `generator: ${label}`,
    );
  }
});

test('validated method policy is a detached deeply frozen authority', async () => {
  const [, , policyBytes] = await canonicalSources();
  const input = JSON.parse(policyBytes.toString('utf8'));
  const validated = validateMethodPolicy(input);
  const originalTimeout = validated.methods['runtime.send'].defaultTimeoutMs;

  assert.notEqual(validated, input);
  assert.notEqual(validated.methods, input.methods);
  assert.equal(Object.isFrozen(validated), true);
  assert.equal(Object.isFrozen(validated.methods), true);
  for (const entry of Object.values(validated.methods)) assert.equal(Object.isFrozen(entry), true);

  input.methods['runtime.send'].defaultTimeoutMs = 1;
  assert.equal(validated.methods['runtime.send'].defaultTimeoutMs, originalTimeout);
});

test('canonical paths keep manifest, fixtures, and policy out of the JSON Schema directory', () => {
  assert.equal(path.relative(contractsRoot, desktopContractPaths.manifest).replaceAll('\\', '/'), 'desktop/native-bridge-manifest.v1.json');
  assert.equal(path.relative(contractsRoot, desktopContractPaths.fixtures).replaceAll('\\', '/'), 'desktop/fixtures/native-bridge-fixtures.v1.json');
  assert.equal(path.relative(contractsRoot, desktopContractPaths.policy).replaceAll('\\', '/'), 'desktop/runtime-method-policy.v1.json');
});
