// Generated by scripts/generate-organization-v3-types.mjs. Do not edit.
// schema-bundle-sha256: fa0aa1384edc6bf16f47945fb05f37cd132d47e8546de90f4f250d4ab5920fc6

export type AgentLifecycleState = "proposed" | "provisioning" | "active" | "retired" | "superseded";

export type AgentOrigin = "foundation" | "user" | "controller" | "workflow" | "inspection";

export type AgentCreationRefKind = "task" | "workflow_run" | "project_bootstrap" | "migration" | "user" | "organization_decision" | "inspection";

export type AgentCreationRef = {
  kind: "task" | "workflow_run" | "project_bootstrap" | "migration" | "user" | "organization_decision" | "inspection";
  id: string;
};

export type AgentV3 = {
  agent_id: string;
  role_id: string;
  role_version: number;
  mission: string | null;
  context_scope: Array<string>;
  lifecycle_state: "proposed" | "provisioning" | "active" | "retired" | "superseded";
  origin: "foundation" | "user" | "controller" | "workflow" | "inspection" | null;
  created_from_ref: {
    kind: "task" | "workflow_run" | "project_bootstrap" | "migration" | "user" | "organization_decision" | "inspection";
    id: string;
  } | null;
  retired_at: string | null;
};

export type AgentRegistryV3 = {
  schema_version: 3;
  organization_revision: number;
  agents: Array<{
    agent_id: string;
    role_id: string;
    role_version: number;
    mission: string | null;
    context_scope: Array<string>;
    lifecycle_state: "proposed" | "provisioning" | "active" | "retired" | "superseded";
    origin: "foundation" | "user" | "controller" | "workflow" | "inspection" | null;
    created_from_ref: {
      kind: "task" | "workflow_run" | "project_bootstrap" | "migration" | "user" | "organization_decision" | "inspection";
      id: string;
    } | null;
    retired_at: string | null;
  }>;
};

export type CoordinationMode = "peer" | "supervised" | "workflow_managed";

export type OrganizationReferenceKind = "participant" | "agent" | "line" | "team";

export type OrganizationReferenceV3 = {
  kind: "participant" | "agent" | "line" | "team";
  id: string;
};

export type OrganizationParticipantV3 = {
  participant_id: string;
  display_name: string;
  participant_kind: "human";
  lifecycle_state: "active" | "inactive" | "retired";
  joined_at: string | null;
};

export type OrganizationLineV3 = {
  line_id: string;
  display_name: string;
  goal: string;
  deliverable_ids: Array<string>;
  completion_root_ids: Array<string>;
  scope: Array<string>;
  owner_ref: {
    kind: "participant" | "agent";
    id: string;
  };
  status: "active" | "paused" | "retired";
  approval_source: "user_approval" | "organization_decision" | "migrated_legacy";
};

export type OrganizationTeamV3 = {
  team_id: string;
  line_id: string | null;
  display_name: string;
  purpose: string;
  coordination_mode: "peer" | "supervised" | "workflow_managed";
  lead_agent_id: string | null;
  lifecycle_state: "active" | "retired";
};

export type OrganizationMembershipV3 = {
  membership_id: string;
  agent_id: string;
  team_id: string;
  position: "member" | "lead";
  ordinal: number;
  active_from: string;
  active_to: string | null;
};

export type OrganizationRelationshipV3 = {
  relationship_id: string;
  type: "reports_to" | "authority_over" | "supports";
  subject_ref: {
    kind: "participant" | "agent" | "line" | "team";
    id: string;
  };
  object_ref: {
    kind: "participant" | "agent" | "line" | "team";
    id: string;
  };
};

export type OrganizationPolicyV3 = {
  line_creation: "autonomous" | "review" | "forbidden";
  max_concurrent_provisioning: number;
  require_executable_task_per_new_agent: true;
  require_no_file_ownership_conflict: true;
};

export type OrganizationStateV3 = {
  schema_version: 3;
  revision: number;
  policy: {
    line_creation: "autonomous" | "review" | "forbidden";
    max_concurrent_provisioning: number;
    require_executable_task_per_new_agent: true;
    require_no_file_ownership_conflict: true;
  };
  participants: Array<{
    participant_id: string;
    display_name: string;
    participant_kind: "human";
    lifecycle_state: "active" | "inactive" | "retired";
    joined_at: string | null;
  }>;
  lines: Array<{
    line_id: string;
    display_name: string;
    goal: string;
    deliverable_ids: Array<string>;
    completion_root_ids: Array<string>;
    scope: Array<string>;
    owner_ref: {
      kind: "participant" | "agent";
      id: string;
    };
    status: "active" | "paused" | "retired";
    approval_source: "user_approval" | "organization_decision" | "migrated_legacy";
  }>;
  teams: Array<{
    team_id: string;
    line_id: string | null;
    display_name: string;
    purpose: string;
    coordination_mode: "peer" | "supervised" | "workflow_managed";
    lead_agent_id: string | null;
    lifecycle_state: "active" | "retired";
  }>;
  memberships: Array<{
    membership_id: string;
    agent_id: string;
    team_id: string;
    position: "member" | "lead";
    ordinal: number;
    active_from: string;
    active_to: string | null;
  }>;
  relationships: Array<{
    relationship_id: string;
    type: "reports_to" | "authority_over" | "supports";
    subject_ref: {
      kind: "participant" | "agent" | "line" | "team";
      id: string;
    };
    object_ref: {
      kind: "participant" | "agent" | "line" | "team";
      id: string;
    };
  }>;
  applied_decision_ids: Array<string>;
  applied_decision_bindings: Array<{
    decision_id: string;
    content_hash: string;
  }>;
};

export type FormationReferenceKind = "project" | "line" | "team" | "agent" | "task" | "workflow_run";

export type FormationReferenceV3 = {
  kind: "project" | "line" | "team" | "agent" | "task" | "workflow_run";
  id: string;
};

export type FormationV3 = {
  formation_id: string;
  formation_kind: "work_cell" | "inspection";
  source_ref: {
    kind: "task" | "workflow_run";
    id: string;
  };
  scope_ref: {
    kind: "project" | "line" | "team" | "agent" | "task" | "workflow_run";
    id: string;
  };
  member_agent_ids: Array<string>;
  coordination_mode: "peer" | "supervised" | "workflow_managed";
  lead_agent_id: string | null;
  target_refs: Array<{
    kind: "project" | "line" | "team" | "agent" | "task" | "workflow_run";
    id: string;
  }>;
  lifecycle_state: "active" | "retired";
  created_at: string;
  retired_at: string | null;
};

export type FormationState = {
  schema_version: 1;
  organization_revision: number;
  formations: Array<{
    formation_id: string;
    formation_kind: "work_cell" | "inspection";
    source_ref: {
      kind: "task" | "workflow_run";
      id: string;
    };
    scope_ref: {
      kind: "project" | "line" | "team" | "agent" | "task" | "workflow_run";
      id: string;
    };
    member_agent_ids: Array<string>;
    coordination_mode: "peer" | "supervised" | "workflow_managed";
    lead_agent_id: string | null;
    target_refs: Array<{
      kind: "project" | "line" | "team" | "agent" | "task" | "workflow_run";
      id: string;
    }>;
    lifecycle_state: "active" | "retired";
    created_at: string;
    retired_at: string | null;
  }>;
};

export type PlacementIntent = {
  placement_intent_id: string;
  purpose: string;
  capability_needs: Array<string>;
  scope_ref: {
    kind: "project" | "line" | "team" | "agent" | "task" | "workflow_run";
    id: string;
  };
  lifetime: "persistent" | "task" | "workflow_run" | "one_shot";
  requested_count: number;
  coordination_hint: "peer" | "supervised" | "workflow_managed" | null;
  source_ref: {
    kind: "project" | "user" | "task" | "workflow_run";
    id: string;
  };
};

export type PlacementTaskV3 = {
  task_id: string;
  task_kind: "specialist_work";
  placement_intent_id: string;
  assigned_agent_id: string;
  owner_agent_id: string;
  role_id: string;
  role_version: number;
  purpose: string;
  acceptance_criteria: Array<string>;
  state: "queued" | "assigned" | "dispatch_accepted" | "turn_started" | "in_progress" | "blocked" | "failed" | "needs_orchestrator_review" | "needs_revision" | "accepted" | "cancelled" | "superseded";
  dependencies: Array<string>;
  blocked_by: Array<string>;
  result_summary: string | null;
  accepted_at: string | null;
  specialist_report_required: true;
  created_at: string;
  updated_at: string;
  placement_fingerprint: string;
};

export type PlacementTaskStateV3 = {
  schema_version: 3;
  project_id: string;
  revision: number;
  tasks: Array<{
    task_id: string;
    task_kind: "specialist_work";
    placement_intent_id: string;
    assigned_agent_id: string;
    owner_agent_id: string;
    role_id: string;
    role_version: number;
    purpose: string;
    acceptance_criteria: Array<string>;
    state: "queued" | "assigned" | "dispatch_accepted" | "turn_started" | "in_progress" | "blocked" | "failed" | "needs_orchestrator_review" | "needs_revision" | "accepted" | "cancelled" | "superseded";
    dependencies: Array<string>;
    blocked_by: Array<string>;
    result_summary: string | null;
    accepted_at: string | null;
    specialist_report_required: true;
    created_at: string;
    updated_at: string;
    placement_fingerprint: string;
  }>;
};

export type OrganizationAgentPlacementPersistentV1 = {
  purpose: string;
  capability_needs: Array<string>;
  role_ref: {
    id: string;
    version: number;
  };
  scope_ref: {
    kind: "project" | "line" | "team";
    id: string;
  };
  requested_count: number;
  coordination_hint: "peer" | "supervised" | null;
};

export type SessionBindingHandoffStatus = "pending" | "accepted" | "failed";

export type SessionBindingRotationState = "active" | "rotation_preparing" | "rotation_pending" | "rotation_required" | "draining" | "checkpointed" | "successor_warming" | "successor_verified" | "superseded" | "failed" | "retired";

export type SessionBindingOwnershipStatus = "owner" | "candidate" | "superseded" | "retired";

export type SessionBindingStatus = "bound" | "provisioning" | "authority_unverified" | "conflict";

export type SessionBindingVisibility = "codex_task" | "desktop_only";

export type SessionBindingV1 = {
  session_id: string;
  agent_id: string;
  thread_id: string;
  session_generation: number;
  session_kind: "persistent_agent";
  attachment_tool_state?: "supported" | "unsupported";
  handoff_status: "pending" | "accepted" | "failed";
  handoff_turn_id: string | null;
  accepted_at: string | null;
  rotation_state: "active" | "rotation_preparing" | "rotation_pending" | "rotation_required" | "draining" | "checkpointed" | "successor_warming" | "successor_verified" | "superseded" | "failed" | "retired";
  ownership_status: "owner" | "candidate" | "superseded" | "retired";
  accepts_new_work: boolean;
  binding_status: "bound" | "provisioning" | "authority_unverified" | "conflict";
  replaces_session_id: string | null;
  replaced_by_session_id: string | null;
  retry_of_session_id: string | null;
  visibility: "codex_task" | "desktop_only";
  profile_id: string;
  runtime_authority_id: string | null;
  provisioning_request_id: string | null;
  placement_intent_id: string | null;
  task_id: string | null;
  ownership_started_at: string | null;
  ownership_ended_at: string | null;
  created_at: string;
  updated_at: string;
};

export type SessionBindingStateV1 = {
  schema_version: 1;
  project_id: string;
  revision: number;
  sessions: Array<{
    session_id: string;
    agent_id: string;
    thread_id: string;
    session_generation: number;
    session_kind: "persistent_agent";
    attachment_tool_state?: "supported" | "unsupported";
    handoff_status: "pending" | "accepted" | "failed";
    handoff_turn_id: string | null;
    accepted_at: string | null;
    rotation_state: "active" | "rotation_preparing" | "rotation_pending" | "rotation_required" | "draining" | "checkpointed" | "successor_warming" | "successor_verified" | "superseded" | "failed" | "retired";
    ownership_status: "owner" | "candidate" | "superseded" | "retired";
    accepts_new_work: boolean;
    binding_status: "bound" | "provisioning" | "authority_unverified" | "conflict";
    replaces_session_id: string | null;
    replaced_by_session_id: string | null;
    retry_of_session_id: string | null;
    visibility: "codex_task" | "desktop_only";
    profile_id: string;
    runtime_authority_id: string | null;
    provisioning_request_id: string | null;
    placement_intent_id: string | null;
    task_id: string | null;
    ownership_started_at: string | null;
    ownership_ended_at: string | null;
    created_at: string;
    updated_at: string;
  }>;
};

export type OrganizationV3Bundle = {

  agentRegistry: AgentRegistryV3;

  organization: OrganizationStateV3;

  formations: FormationState;

};

export type OrganizationV3ContractMap = {

  "agent-registry-v3": AgentRegistryV3;

  "organization-state-v3": OrganizationStateV3;

  "formation-state": FormationState;

  "organization-agent-placement-persistent-v1": OrganizationAgentPlacementPersistentV1;

  "placement-intent": PlacementIntent;

  "placement-task-state-v3": PlacementTaskStateV3;

};

export type SessionBindingContractMap = {

  "session-binding-state-v1": SessionBindingStateV1;

};

export type CanonicalContractMap = OrganizationV3ContractMap & SessionBindingContractMap;
